apiVersion: apps/v1
kind: Deployment
metadata:
  name: lingoda
  namespace: default # Namespace to deploy the application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lingoda
  template:
    metadata:
      labels:
        app: lingoda
    spec:
      # Image pull secret to access private registry
      imagePullSecrets:
        - name: regcred
      containers:
        - name: lingoda
          image: forevertga/lingoda:v1
          ports:
            - containerPort: 8000
