apiVersion: v1
kind: Service
metadata:
  name: lingoda
  labels:
    app: lingoda
  namespace: default
spec:
  # type: NodePort
  selector:
    app: lingoda
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      # nodePort: 30000
